FullStackDjango/MyProject/urls.py
from django.contrib import admin
from django.urls import path,include

#Bij '' kan je ook alle URLS gebruiken van api.urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('api.urls'))

]

FullStackDjango/api/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView

app_name = "api"

urlpatterns =  [
    path('home', views.Home, name="home-page"),
    path('register/', views.Register, name="registration-page"),
    path('', views.login_view, name="login"),
    path('logout', views.logout_view),
    path('products', views.products, name='products'),
    path('products/<str:selectedCategory>/', views.products, name='products'),
    path('products/<str:selectedCategory>/<str:selectedBrand>', views.products, name='products'),
    path('products/my-recommended-products', views.productsRecommended, name="productsRecommended"),
    path('productDetail', views.productDetail, name="productDetail"),
    path('productDetail/<int:productId>/', views.productDetail, name="productDetail"),
    path('productDetail/<int:productId>/order', views.addOrder, name="productDetail"),
    path('knn', views.PreInfoKnn, name="disclamer-algoritm-page"),
    path('knn/index', views.TopRecommendation, name="algorithm-page"),
    path('knn/<int:userId>/', views.Knn, name="knn-page"),
    path('orders', views.orderHistory, name="orderhist-page")
]

FullStackDjango/api/models.py
from django.db import models
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager)
from django import forms

from django.contrib.auth.models import AbstractBaseUser
from rest_framework import serializers

# Create your models here.
#Models + __str__ dat ervoor zorgt dat hij bij een call de naam laat zien.
class Author(models.Model):
  name = models.CharField(max_length=255)
  email = models.EmailField()
  def __str__(self):
      return self.name


class Article(models.Model):
    title = models.CharField(max_length=120)
    description = models.TextField()
    body = models.TextField()
    author = models.ForeignKey('Author', related_name='articles', on_delete=models.PROTECT)
    def __str__(self):
        return self.title

class Product(models.Model):
    title = models.CharField(max_length=120)
    brand = models.CharField(max_length=30)
    image = models.TextField()
    price = models.FloatField()
    category = models.CharField(max_length=30)
    def __str__(self):
        return self.title

class ProductList(models.Model):
    product = models.ForeignKey('Product', related_name='products', on_delete=models.CASCADE)
    order = models.ForeignKey('Order', related_name='orders', on_delete=models.CASCADE)
    amount = models.IntegerField()


class Order(models.Model):
    user = models.ForeignKey('User', related_name='user', on_delete=models.CASCADE)
    def __str__(self):
      return self.user


#---------------------------------- USER MODEL ---------------------------------------------
class UserManager(BaseUserManager):
    def create_user(self, email, password=None, is_active=True, is_staff= False, is_admin=False, **extra_fields):
        if not email :
            raise ValueError("Users must have an email address")
        if not password:
            raise ValueError("Users must have a password")
        user_obj = self.model(email = self.normalize_email(email), **extra_fields)
        user_obj.set_password(password)
        user_obj.staff = is_staff
        user_obj.admin = is_admin
        user_obj.active = is_active
        user_obj.save(using= self._db)
        return user_obj

    def create_staffuser(self, email, password=None):
        user = self.create_user(email, password=password, is_staff=True)
        return user

    def create_superuser(self, email, password=None):
        user = self.create_user(email, password=password, is_staff=True, is_admin=True)
        return user
    
    

class User(AbstractBaseUser):
    Job_title_choices = [('Developer', 'Developer'),
                         ('Designer', 'Designer'),
                         ('Office', 'Office')
                        ]

    email = models.EmailField(max_length=255, unique=True)
    active = models.BooleanField(default=True)
    staff = models.BooleanField(default=False)
    admin = models.BooleanField(default=False)
    jobtitle = models.CharField(max_length=255, choices=Job_title_choices)
    firstname = models.CharField(max_length=255, blank=True)
    lastname = models.CharField(max_length=255, blank=True)
    timestamp = models.DateField(auto_now_add=True)

    USERNAME_FIELD = 'email'
    #This replaces the username field(which normally is used bij default) with email

    REQUIRED_FIELDS = []

    def get_mail(self):
        return self.email
    
    def get_full_name(self):
        return '%s %s' % (self.firstname, self.lastname)

    def get_first_name(self):
        return self.firstname

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.staff

    @property
    def is_admin(self):
        return self.admin
    
    @property
    def is_active(self):
        return self.active

    objects = UserManager()


    


    

FullStackDjango/api/forms.py
from django import forms
from .models import User
from django.contrib.auth.forms import UserCreationForm
from django.db import models
from django.contrib.auth import authenticate

class RegistrationForm(UserCreationForm):
    Job_title_choices = [('Developer', 'Developer'),
                         ('Designer', 'Designer'),
                         ('Office', 'Office')
                        ]
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={ 'placeholder': 'example@gmail.com'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Enter password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Enter password'}))
    firstname = forms.CharField(required=True, widget=forms.TextInput(attrs={'placeholder': 'John'}))
    lastname = forms.CharField(required=True, widget=forms.TextInput(attrs={'placeholder': 'Doe'}))
    jobtitle = forms.ChoiceField(choices=Job_title_choices, widget=forms.RadioSelect(attrs={}))


    class Meta:
        model = User
        fields = ('email', 'firstname', 'lastname', 'jobtitle', 'password1', 'password2')

    
    
    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.firstname = self.cleaned_data['firstname']
        user.lastname = self.cleaned_data['lastname']
        user.email = self.cleaned_data['email']

        if User.objects.filter(email=self.cleaned_data['email']).count() != 0:
            raise forms.ValidationError("Email already exists")
        
        if commit:
            user.save()
        return user

class LoginForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Enter Email'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Enter Password'}))

    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        if email and password:
            user = authenticate(email=email, password=password)
            if not user:
                raise forms.ValidationError('Invalid Email or Password')
        return super(LoginForm, self).clean(*args, **kwargs)

FullStackDjango/api/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.db import connection
from django.http import HttpResponse, HttpResponseRedirect
from api.forms import RegistrationForm, LoginForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, get_user_model, login, logout
from .Recommender import Recommender

from django.http import HttpRequest
from django.template import RequestContext
from .models import User, Product, Order, ProductList
from rest_framework.response import Response
from rest_framework.views import APIView
# from .serializers import ArticleSerializer
# Create your views here.


def PreInfoKnn(request):
    return render(request, 'algorithmDisclaimer.html')

# this path is for entering the algorithm view. however no user is selected therefore it returns top 10 recommend items
def TopRecommendation(request):
    dev = User.objects.all().filter(jobtitle = "Developer")      
    des = User.objects.all().filter(jobtitle = "Designer")
    off = User.objects.all().filter(jobtitle = "Office")
    test = Recommender(5)
    products = test.GetTopBorrowedItems(10)
    print(products)
        
    return render(request, 'topItem.html', {'products': products, 'developers': dev, 'designers': des, 'office': off})

def Knn(request, userId):
    #get selected user information 
    query = connection.cursor().execute("SELECT * FROM api_user WHERE id =" + str(userId))
    currentUser = query.fetchall()

    #Get UserHistory
    recommender = Recommender(userId)
    hist, haveHist = recommender.CheckAndGetHistory()
    recommendList = recommender.Knn(hist)

    print(currentUser)
    dev = User.objects.all().filter(jobtitle = "Developer")      
    des = User.objects.all().filter(jobtitle = "Designer")
    off = User.objects.all().filter(jobtitle = "Office") #required for side menu
    return render(request, 'knn.html', {'developers': dev, 'designers': des, 'office': off, 'currentUser': currentUser, 'history': haveHist, 'recommend': recommendList})

@login_required(login_url='/')
def Home(request):
    id = request.user.id
    query = connection.cursor().execute("SELECT * FROM api_user WHERE id =" + str(id))
    currentUser = query.fetchall()
    print()

    #Get UserHistory
    recommender = Recommender(id)
    hist, haveHist = recommender.CheckAndGetHistory()
    recommendList = recommender.Knn(hist)
    #Gooit het resultaat van Id's in een lijst en pakt alle producten met die Id's. 
    idList = []
    Recommended = []
    for item in recommendList:
        idList.append(item[0])
    for item in idList:
        query = connection.cursor().execute("SELECT * FROM api_product WHERE id =" + str(item))
        product = query.fetchall()
        Recommended.append(product)


    return render(request, "home.html", {'product' : Recommended})

def Register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/home')
    else:
        form = RegistrationForm()   
    return render(request, 'register.html', {'form': form})

def login_view(request):
    next = request.GET.get('next')
    form = LoginForm(request.POST or None)
    if form.is_valid():
        email = form.cleaned_data.get('email')
        password = form.cleaned_data.get('password')
        user = authenticate(email=email, password=password)
        login(request, user)
        if next:
            return redirect(next)
        return redirect('/home')
    return render(request, "login.html", {'form': form})


def logout_view(request):
    logout(request)
    return redirect('/')



## Webpagina die Db info laat zien ##
@login_required(login_url='/')
def products(request, selectedCategory, selectedBrand):
    if selectedCategory == '0':
        Product_list = Product.objects.all() ## Product List = Variabel, Objects.all() pakt alle producten in de DB ##
    elif selectedBrand == '0': 
        query = connection.cursor().execute("SELECT * FROM api_product WHERE category = '" + str(selectedCategory) + "'")
        Product_list = query.fetchall()
    else:
        query = connection.cursor().execute("SELECT * FROM api_product WHERE category = '" + str(selectedCategory) + "' AND brand = '" + str(selectedBrand) + "'")
        Product_list = query.fetchall()

       


    page = request.GET.get('page', 1)
    paginator = Paginator(Product_list, 10)
    try:
        product = paginator.page(page)
    except PageNotAnInteger:
        product = paginator.page(1)
    except EmptyPage:
        product = paginator.page(paginator.num_pages)

    
    query = connection.cursor().execute("SELECT category FROM api_product GROUP BY category")
    categories = query.fetchall()

    if selectedCategory != '0':
          query = connection.cursor().execute("SELECT brand FROM api_product WHERE category = '" + str(selectedCategory) + "'GROUP BY brand")
          brands = query.fetchall()  
    
    if selectedCategory == '0':
        return render(request, 'api/products.html', {'Product': product, 'Categories': categories, 'enabledCategories': False}) 
    else:
        return render(request, 'api/products.html', {'Product': product, 'Categories': categories, 'enabledCategories': True, 'currentCategorie': str(selectedCategory), 'Brands': brands}) 
    

@login_required(login_url='/')
def productsRecommended(request):
    #get selected user information 
    id = request.user.id
    query = connection.cursor().execute("SELECT * FROM api_user WHERE id =" + str(id))
    currentUser = query.fetchall()
    print()

    #Get UserHistory
    recommender = Recommender(id)
    hist, haveHist = recommender.CheckAndGetHistory()
    recommendList = recommender.Knn(hist)
    #Gooit het resultaat van Id's in een lijst en pakt alle producten met die Id's. 
    idList = []
    Recommended = []
    for item in recommendList:
        idList.append(item[0])
    for item in idList:
        query = connection.cursor().execute("SELECT * FROM api_product WHERE id =" + str(item))
        product = query.fetchall()
        Recommended.append(product)


    return render(request, 'api/products.html', {'Product': Recommended, 'Recommended': True})

@login_required(login_url='/')
def productDetail(request, productId):
        query = connection.cursor().execute("SELECT * FROM api_product WHERE id =" + str(productId))
        product = query.fetchall()
        return render(request, 'api/detailPage.html',{'Product': product})

@login_required(login_url='/')
def orderHistory(request):
    id = request.user.id
    print(id)
    orderHistory = []
    query = connection.cursor().execute("SELECT api_order.id, api_productlist.product_id, api_product.title, api_product.image, api_product.id, api_productlist.amount, api_product.category FROM api_order JOIN api_productlist ON api_order.id = api_productlist.order_id JOIN api_product ON api_productlist.product_id == api_product.id WHERE user_id =" + str(id) + " ORDER BY api_order.id DESC")
    orderList = query.fetchall()
    print(orderList)
    
    userQuery = connection.cursor().execute("SELECT * FROM api_user Where id = " + str(id)) 
    user = userQuery.fetchall()
    page = request.GET.get('page', 1)
    paginator = Paginator(orderList, 10)
    try:
        product = paginator.page(page)
    except PageNotAnInteger:
        product = paginator.page(1)
    except EmptyPage:
        product = paginator.page(paginator.num_pages)


    return render(request, 'api/orderHistoryPage.html', {'OrderHistory': product, 'User': user })


@login_required(login_url='/')
def addOrder(request, productId):
    id = request.user.id
    print("This is product ID: " + str(productId))
    query = connection.cursor().execute("select * from api_product where id =" + str(productId))
    Found = query.fetchall()
   
    newOrder = Order.objects.create(user = request.user)
    
    myorder = Order.objects.latest('id')
    myorderId = myorder

    productInstance = Product.objects.get(title = str(Found[0][1]))
    
    addProduct = ProductList.objects.create(product = productInstance , order = myorderId, amount = 1 )

    return render(request, 'api/detailPageOrder.html',{'Product': Found, 'Order': myorderId.id})

FullStackDjango/api/templates/api/detailPage.html
{% extends "api/shared.html" %}
{% block content %}

<header>
  <!-- Your custom styles (optional) -->
  <link href="/static/detailPage.css" rel="stylesheet">
</header>

 <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">
            <img class="img-fluid" src="{{Product.0.3}}"/>

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4 ">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <h3>{{Product.0.1}}</h3>
            </div>

            <p>{{Product.0.2}}</p>
            <p class="lead">
              <span>€ {{Product.0.4}}</span>
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Et dolor suscipit libero eos atque quia ipsa
              sint voluptatibus!
              Beatae sit assumenda asperiores iure at maxime atque repellendus maiores quia sapiente.</p>

            <form class="d-flex justify-content-left">
              <!-- Default input -->
              <input type="number" name="amount" value="1" aria-label="Search" class="form-control" hidden="hidden" min="1" max="5" style="width: 100px" required>
                <span> </span>
              <input name="productId" value="{{Product.0.0}}" hidden="hidden"/>
                <!-- Trigger modal with Reserve button -->
                <a  href="/productDetail/{{Product.0.0}}/order"><button class="btn btn-dark btn-md my-0 ml-1" type="button">Reserve          
              </button></a>

              
            </form>
          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex ml-5 wow fadeIn">

        <!--Grid column-->
        <div class="col-md-10 text-left pb-5">

          <h4 class="my-4 h4">Description</h4>

          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

        </div>
        <!--Grid column-->

      </div>

    </div>

 </main>
{% endblock %}

FullStackDjango/api/templates/api/products.html
{% extends "api/shared.html" %}
{% block content %}

<head>
<link rel="stylesheet" href="/static/product.css">
<title> DB Data (read from database)</title>
</head>
    <body>
        

<div class="container py-3"  >
  <div class="row">
    <div class="col-3 card h-50 d-inline-block"> <!-- style="background-color:lightgray"-->
      <article class="card-group-item">
          <header class="mx-auto">
            {% if enabledCategories == False %}
            <h4 class="text-center"> Products</h4>
            {% elif Recommended == True%}
            <h5 class="text-center">Recommended Products</h5>
            {% else %}
            <h4 class="text-center">{{currentCategorie}}</h4>
            {% endif %}
          </header>
          <ul class="list-group list-group-flush">
              <a href="{% url 'api:products'%}/0/0">  
                  <li class="list-group-item">
                    Show all items
                  </li>
              </a>
                {% for item in Categories %}
              <a href="{% url 'api:products'%}/{{item.0}}/0" class="py-1">
                <li class="list-group-item ">
                    {{item.0}}
                </li>
              </a>

                {% endfor %}
                </br>
                <!-- Brands -->
                {% if enabledCategories == True%}
                <h5 class="text-center">Brands</h5>
                {% for item in Brands %}
                <a href="{% url 'api:products'%}/{{currentCategorie}}/{{item.0}}"  class="py-1">
                    <li class="list-group-item">
                        {{item.0}}
                    </li>
                </a>
                {% endfor %}
                <br />
                {% endif %}

                {% if Recommended != True%}
                <a href="{% url 'api:products'%}/my-recommended-products">
                <li class="list-group-item">
                    Show recommended
                </li>
                </a>
                {% endif %}
          </ul>
      </article>
      <!-- Categorieeren-->

    </div>
      <!-- PRODUCTEN ZONDER FILTER OF RECOMMENDATIE-->
      {% if Product%}
    <div class="col-9">
        <div class="container">
            {% if Recommended != True and enabledCategories == False%}
            
            {% for item in Product%}
            <div class="row" >
                <div class="col-3 py-4"> <!--style="background-color: #d5f4e6;" -->
                    <div class="block">
                    {% if item.category == "Mobile" or item.category == "Mouse"   %}
                    <img class="img-left" src="{{item.image}}" style="float:left" width="150" height=150"/>
                    {% else %}
                    <img class="img-left" src="{{item.image}}" style="float:left" width="150" height=100"/>
                    {% endif%}
                    </div>
                </div>
                <div class="col-9 py-2"> <!--style="background-color: #4cff00;" -->
                    
                     {{item.title}}
                    </br>
                     Merk: {{item.brand}}
                    </br>
                     Prijs: &euro;{{item.price}}
                    </br>
                    <a href="{% url 'api:productDetail'%}/{{item.id}}"><button class="btn btn-dark mt-1">More</button></a>

                </div>
                    <div class="col-sm-12">
                    <div style='border-bottom:2px solid #ccc;'></div>
                    </div>                
            </div>

            {% endfor %}
            <!-- PRODUCTEN ZONDER FILTER MAAR MET RECOMMENDATIE-->
            {% elif Recommended == True%}
                        {% for item in Product%}
            <div class="row" >
                <div class="col-3 py-4"> <!--style="background-color: #d5f4e6;" -->
                    <div class="block">
                    {% if item.0.5 == "Mobile" or item.0.5 == "Mouse"   %}
                    <img class="img-left" src="{{item.0.3}}" style="float:left" width="150" height=150"/>
                    {% else %}
                    <img class="img-left" src="{{item.0.3}}" style="float:left" width="150" height=100"/>
                    {% endif%}
                    </div>
                </div>
                <div class="col-9 py-2"> <!--style="background-color: #4cff00;" -->
                    
                    {{item.0.1}}
                    </br>
                    Merk: {{item.0.2}}
                    </br>
                    Prijs: &euro;{{item.0.4}}
                    </br>
                    <a href="{% url 'api:productDetail'%}/{{item.0.0}}"><button class="btn btn-dark mt-1">More</button></a>
                     

                </div>
                <div class="col-sm-12">
                <div style='border-bottom:2px solid #ccc;'></div>
                </div>
            </div>
            {% endfor %}

            {% else %}
            <!-- PRODUCTEN MET FILTER ZONDER RECOMMENDATIE-->
            {% for item in Product%}
            <div class="row" >
                <div class="col-3 py-4"> <!--style="background-color: #d5f4e6;" -->
                    <div class="block">
                    {% if item.5 == "Mobile" or item.5 == "Mouse"   %}
                    <img class="img-left" src="{{item.3}}" style="float:left" width="150" height=150"/>
                    {% else %}
                    <img class="img-left" src="{{item.3}}" style="float:left" width="150" height=100"/>
                    {% endif%}
                    </div>
                </div>
                <div class="col-9 py-2"> <!--style="background-color: #4cff00;" -->
                    
                    {{item.1}}
                    </br>
                    Merk: {{item.2}}
                    </br>
                    Prijs: &euro;{{item.4}}
                    </br>
                    <a href="{% url 'api:productDetail'%}/{{item.0}}"><button class="btn btn-dark mt-1">More</button></a>
                     

                </div>
                <div class="col-sm-12">
                <div style='border-bottom:2px solid #ccc;'></div>
                </div>
            </div>
            {% endfor %}
            {% endif %}

            <div class="mx-auto pt-3">
            {% if Product.has_other_pages %}
              <ul class="pagination justify-content-center">
                {% if Product.has_previous %}
                  <li class="page-item"><a class="page-link" href="?page={{ Product.previous_page_number }}">&laquo;</a></li>
                {% else %}
                  <li class="disabled page-item"><a class="page-link" href="?page=">&laquo;</a></li>
                {% endif %}
                {% for i in Product.paginator.page_range %}
                  {% if Product.number == i %}
                    <li class="active page-item disabled"><a class="page-link" href="?page=">{{ i }}</a></li>
                  {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                  {% endif %}
                {% endfor %}
                {% if Product.has_next %}
                  <li class="page-item"><a class="page-link" href="?page={{ Product.next_page_number }}">&raquo;</a></li>
                {% else %}
                  <li class="disabled page-item"><a class="page-link" href="?page=">&raquo;</a></li>
                {% endif %}
              </ul>
            {% endif %}
            </div>
            </div>
        </div>
    </div>
    {% endif %}
  </div>
    </body>

{% endblock %}
    

FullStackDjango/api/templates/api/shared.html
{# Laad de statische bestanden, dit is alles in de static folders. #}
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link href="/static/scripts/shared.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <title>Dept - Lending Page</title>
        <script type="text/javascript">
    $(window).on("load", function () {
        $("#myModal").modal("show");
    });
    </script>
</head>

<body>
    <div id="main">
    <nav class="navbar navbar-expand-sm navbar-dark bg">
        <div class="container">
            <!-- <a class="navbar-brand logo " href="/"><h2>HotBunsJS</h2></a> -->
            <a class="navbar-brand logo" href="{% url 'api:home-page'%}"><h2>Dept</h2></a>
                {# Via static pakt hij het plaatje uit de static folder. Dit is verplicht. #}

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav">

                    <li class="nav-item mr-4 ml-4">
                        <a class="nav-link font-weight-bold" style="color:lightgray" href="{% url 'api:home-page'%}">Home</a>
                    </li>
                    <li class="nav-item mr-4 ml-4">
                        <a class="nav-link font-weight-bold" style="color:lightgray" href="{% url 'api:products' %}/0/0">Browse</a>
                    </li>
                    <li class="nav-item mr-4 ml-4">
                        <a class="nav-link font-weight-bold" style="color:lightgray" href="{% url 'api:orderhist-page' %}">Orders</a>
                    </li>
                    <li class="nav-item mr-4 ml-4">
                            <a class="nav-link font-weight-bold" style="color:lightgray" href="/logout">Logout</a>
                    </li>
                </ul>

                <ul class="navbar-nav ml-auto">
                 <li class="nav-item mr-2 ml-2">
                     {# Hier plakt hij alle data uit loginpartial.html #}

                </ul>

            </div>
        </div>
    </nav>

   {#Tussen wat boven hier en onder hier zit, plaats hij wat in het gebied genaamt content zit. Hiervoor moet je dus alles een block geven#}
    {% block content %}{% endblock %}

<!-- Footer -->
<footer class="page-footer font-small bg py-3">
    <div class="container">
        <div class="text-center">
            <a href="#" class="mx-2"><i class="fab fa-facebook-square fa-2x" style="color:white"></i></a> 
            <a href="#" class="mx-2"><i class="fab fa-twitter-square fa-2x" style="color:white"></i></a>
            <a href="#" class="mx-2"><i class="fab fa-youtube-square fa-2x" style="color:white"></i></a>
        </div>
        <div class="text-center py-1">
            <a href="#" class="footerAtag mx-2 white">Home</a>
            <a href="#" class="footerAtag mx-2 white">Browse</a>
            <a href="#" class="footerAtag mx-2 white">Account</a>
        </div>
    </div>
    
</footer>
  <!-- Footer -->


    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    </div>
</body>
</html>